"use client";

import { useEffect, useMemo, useState } from "react";
import { Building2, LogOut, MessageCircle, RefreshCw, Search, X } from "lucide-react";

const URL = process.env.NEXT_PUBLIC_SUPABASE_URL || "";
const KEY = process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY || "";
const statuses = ["Novo lead","Contato realizado","Entendendo necessidade","Proposta enviada","Negociação","Cliente ativo","Sem retorno","Perdido","Reativar depois"];

type Lead = { id:string; created_at:string; company:string; contact_name:string; whatsapp:string; email:string; segment:string|null; estimated_meals:string|null; frequency:string|null; service_type:string|null; notes:string|null; status:string; next_follow_up_at:string|null; proposal_value:number|null; owner_notes:string|null };

async function request(path:string, token:string, init:RequestInit={}) {
  const r = await fetch(path,{...init,headers:{apikey:KEY,Authorization:`Bearer ${token}`,"Content-Type":"application/json",...(init.headers||{})}});
  if(!r.ok) throw new Error(await r.text()); return r;
}

export default function AdminPage(){
  const [token,setToken]=useState(""); const [email,setEmail]=useState(""); const [password,setPassword]=useState("");
  const [leads,setLeads]=useState<Lead[]>([]); const [selected,setSelected]=useState<Lead|null>(null);
  const [search,setSearch]=useState(""); const [error,setError]=useState(""); const [busy,setBusy]=useState(false);

  async function load(t=token){ if(!t)return; setBusy(true); try{const r=await request(`${URL}/rest/v1/b2b_leads?select=*&order=created_at.desc`,t);setLeads(await r.json());}catch{sessionStorage.removeItem("nutrifit_admin_token");setToken("");setError("Sessão expirada.");}finally{setBusy(false);}}
  useEffect(()=>{const t=sessionStorage.getItem("nutrifit_admin_token")||"";if(t){setToken(t);void load(t);}},[]);
  async function login(e:React.FormEvent){e.preventDefault();setError("");setBusy(true);try{const r=await request(`${URL}/auth/v1/token?grant_type=password`,"",{method:"POST",body:JSON.stringify({email,password})});const d=await r.json();if(!d.access_token)throw 0;sessionStorage.setItem("nutrifit_admin_token",d.access_token);setToken(d.access_token);setPassword("");await load(d.access_token);}catch{setError("E-mail ou senha inválidos.");}finally{setBusy(false);}}
  async function save(){if(!selected)return;setBusy(true);try{await request(`${URL}/rest/v1/b2b_leads?id=eq.${selected.id}`,token,{method:"PATCH",headers:{Prefer:"return=minimal"},body:JSON.stringify({status:selected.status,next_follow_up_at:selected.next_follow_up_at||null,proposal_value:selected.proposal_value||null,owner_notes:selected.owner_notes||null,last_contact_at:new Date().toISOString()})});await load();setSelected(null);}catch{setError("Não foi possível salvar.");}finally{setBusy(false);}}
  const filtered=useMemo(()=>{const q=search.toLowerCase().trim();return q?leads.filter(x=>[x.company,x.contact_name,x.email,x.whatsapp].join(" ").toLowerCase().includes(q)):leads;},[leads,search]);
  if(!token)return <main className="min-h-screen bg-[#080a07] px-5 py-10 text-white"><div className="mx-auto mt-20 max-w-md rounded-[2rem] border border-white/10 bg-[#10130d] p-8"><Building2 className="text-[#ef7d18]"/><h1 className="mt-4 text-3xl font-black">Painel B2B</h1><p className="mt-2 text-sm text-white/45">Área administrativa da Nutrifit.</p><form onSubmit={login} className="mt-7 grid gap-4"><input required type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="E-mail" className="rounded-xl border border-white/10 bg-white/5 px-4 py-3 outline-none"/><input required type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Senha" className="rounded-xl border border-white/10 bg-white/5 px-4 py-3 outline-none"/>{error&&<p className="text-sm text-red-300">{error}</p>}<button disabled={busy} className="rounded-full bg-[#a7b86a] px-5 py-3.5 font-black text-black">{busy?"Entrando...":"Entrar"}</button></form></div></main>;

  const count=(s:string)=>leads.filter(x=>x.status===s).length;
  return <main className="min-h-screen bg-[#080a07] px-4 py-6 text-white md:px-8"><div className="mx-auto max-w-7xl">
    <header className="flex flex-wrap items-center justify-between gap-4"><div><div className="text-xs font-black uppercase tracking-[.2em] text-[#a7b86a]">Nutrifit</div><h1 className="text-3xl font-black">Painel B2B</h1></div><div className="flex gap-2"><button onClick={()=>void load()} className="rounded-full border border-white/10 px-4 py-2 text-sm"><RefreshCw size={15} className="mr-2 inline"/>Atualizar</button><button onClick={()=>{sessionStorage.removeItem("nutrifit_admin_token");setToken("")}} className="rounded-full border border-white/10 px-4 py-2 text-sm"><LogOut size={15} className="mr-2 inline"/>Sair</button></div></header>
    <section className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[["Leads",leads.length],["Novos",count("Novo lead")],["Propostas/negociação",count("Proposta enviada")+count("Negociação")],["Clientes ativos",count("Cliente ativo")]].map(x=><div key={x[0]} className="rounded-2xl border border-white/10 bg-white/[.035] p-5"><div className="text-3xl font-black">{x[1]}</div><div className="mt-1 text-sm text-white/45">{x[0]}</div></div>)}</section>
    <section className="mt-6 rounded-2xl border border-white/10 bg-white/[.025] p-5"><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="font-black">Leads B2B</h2><label className="flex items-center gap-2 rounded-full border border-white/10 px-3 py-2 text-sm"><Search size={15}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar empresa..." className="w-44 bg-transparent outline-none"/></label></div>
    <div className="mt-4 overflow-x-auto"><table className="w-full min-w-[720px] text-left text-sm"><thead className="text-xs text-white/35"><tr><th className="p-3">Empresa</th><th className="p-3">Contato</th><th className="p-3">Refeições</th><th className="p-3">Status</th><th/></tr></thead><tbody>{filtered.map(l=><tr key={l.id} className="border-t border-white/5"><td className="p-3 font-black">{l.company}</td><td className="p-3">{l.contact_name}<div className="text-xs text-white/35">{l.whatsapp}</div></td><td className="p-3">{l.estimated_meals||"—"}</td><td className="p-3"><span className="rounded-full bg-[#a7b86a]/15 px-2.5 py-1 text-xs">{l.status}</span></td><td className="p-3 text-right"><button onClick={()=>setSelected(l)} className="rounded-full border border-white/10 px-3 py-2 text-xs font-black">Abrir</button></td></tr>)}</tbody></table></div></section>
    {selected&&<div className="fixed inset-0 z-50 flex items-end justify-center bg-black/70 p-3 md:items-center"><div className="max-h-[90vh] w-full max-w-xl overflow-y-auto rounded-[2rem] border border-white/10 bg-[#10130d] p-6"><div className="flex justify-between"><div><div className="text-xs text-[#a7b86a]">LEAD B2B</div><h2 className="text-2xl font-black">{selected.company}</h2><p className="text-sm text-white/45">{selected.contact_name} · {selected.whatsapp}</p></div><button onClick={()=>setSelected(null)}><X/></button></div><div className="mt-6 grid gap-4"><div className="rounded-xl bg-white/[.035] p-4 text-sm">{selected.email}<br/>{selected.estimated_meals||"Refeições não informadas"} · {selected.frequency||"Frequência não informada"}</div><label className="grid gap-2 text-sm font-bold">Status<select value={selected.status} onChange={e=>setSelected({...selected,status:e.target.value})} className="rounded-xl border border-white/10 bg-white/5 px-4 py-3 font-normal">{statuses.map(s=><option key={s}>{s}</option>)}</select></label><label className="grid gap-2 text-sm font-bold">Próximo contato<input type="date" value={selected.next_follow_up_at?.slice(0,10)||""} onChange={e=>setSelected({...selected,next_follow_up_at:e.target.value?`${e.target.value}T12:00:00.000Z`:null})} className="rounded-xl border border-white/10 bg-white/5 px-4 py-3 font-normal"/></label><label className="grid gap-2 text-sm font-bold">Valor da proposta<input type="number" step="0.01" value={selected.proposal_value??""} onChange={e=>setSelected({...selected,proposal_value:e.target.value?Number(e.target.value):null})} className="rounded-xl border border-white/10 bg-white/5 px-4 py-3 font-normal"/></label><label className="grid gap-2 text-sm font-bold">Observações internas<textarea rows={4} value={selected.owner_notes||""} onChange={e=>setSelected({...selected,owner_notes:e.target.value})} className="rounded-xl border border-white/10 bg-white/5 px-4 py-3 font-normal"/></label><div className="flex flex-wrap gap-2"><a href={`https://wa.me/${selected.whatsapp.replace(/\\D/g,"")}`} target="_blank" rel="noreferrer" className="rounded-full border border-[#a7b86a]/30 px-4 py-3 text-sm font-black text-[#d9e5a5]"><MessageCircle className="mr-2 inline" size={16}/>WhatsApp</a><button onClick={()=>void save()} disabled={busy} className="rounded-full bg-[#ef7d18] px-5 py-3 text-sm font-black text-black">{busy?"Salvando...":"Salvar"}</button></div>{selected.notes&&<div className="rounded-xl bg-black/20 p-4 text-sm text-white/55">{selected.notes}</div>}</div></div></div>}
  </div></main>;
}