import { ArrowRight, Check, MessageCircle, ShoppingBag, Sparkles } from "lucide-react";

const whatsapp="https://wa.me/5532998030038?text=Ol%C3%A1%20Nutrifit!%20Quero%20fazer%20um%20pedido.";
const products=[
["Patinho com Abóbora","Fit • 350 g","R$ 19,90","Patinho moído com purê cremoso de abóbora.",0],
["Patinho com Batata-Doce","Fit • 350 g","R$ 19,90","Patinho moído com batata-doce.",1],
["Frango Grelhado com Mix de Legumes","Fit • 350 g","R$ 19,90","Frango grelhado com mix de legumes.",2],
["Carne Acebolada com Legumes","Fit • 350 g","R$ 19,90","Carne acebolada com legumes selecionados.",3],
["Lombo Suíno com Legumes Assados","Fit • 350 g","R$ 19,90","Lombo suíno com legumes assados.",4],
["Frango ao Molho de Ervas com Legumes","Fit • 350 g","R$ 19,90","Frango ao molho de ervas com legumes.",5],
["Frango Cremoso Fit","Tradicional • 500 g","R$ 25,90","Frango cremoso com arroz e legumes.",6],
["Strogonoff Leve de Frango","Tradicional • 500 g","R$ 24,90","Strogonoff leve de frango.",7],
["Churrasco Fit Mineiro","Tradicional • 500 g","R$ 26,90","Contra-filé grelhado, arroz, vinagrete e farofa.",8],
["Parmegiana Cremosa","Tradicional • 500 g","R$ 26,90","Filé de frango, molho de tomate e queijo.",9],
["Feijoada Fit","Tradicional • 500 g","Consultar","Feijoada com lombo e calabresa, arroz, couve e farofa.",10],
["Escondidinho Fit","Tradicional • 500 g","Consultar","Purê cremoso com recheio temperado.",11],
["Beef & Sweet Potato","Performance • 450 g","Consultar","Carne bovina, batata-doce e acompanhamentos.",12],
["Chicken Rice Performance","Performance • 450 g","Consultar","Frango, arroz e legumes.",13],
["Salmão Grelhado","Premium • 500 g","R$ 34,90","Salmão grelhado com arroz e legumes.",14],
["Black Angus + Purê Trufado","Premium • 500 g","R$ 34,90","Black Angus grelhado com purê trufado.",15],
["Salada Summer","Saladas • 350 g","R$ 18,90","Frango, folhas, tomate-cereja, pepino, repolho roxo, cenoura e molho verde.",16],
];
const juices=["Green","Glow","Sun","Energy","Pink","Purple"];
const combos=[["5 marmitas","R$ 109,90"],["7 marmitas","R$ 149,90"],["10 marmitas","R$ 209,90"]];
const pos=(i:number)=>`${(i%4)*33.3333}% ${Math.floor(i/4)*25}%`;
export default function Home(){return <main className="min-h-screen bg-[#090b08] text-white">
<header className="sticky top-0 z-50 border-b border-white/10 bg-[#090b08]/95 backdrop-blur"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-4 md:px-8"><a href="#inicio" className="text-2xl font-black">nutri<span className="text-[#ef7d18]">fit</span></a><nav className="hidden gap-7 text-sm text-white/70 md:flex"><a href="#cardapio">Cardápio</a><a href="#combos">Combos</a><a href="#sucos">Sucos</a><a href="#como-pedir">Como pedir</a></nav><a href={whatsapp} className="inline-flex items-center gap-2 rounded-full bg-[#ef7d18] px-5 py-2.5 text-sm font-black text-black"><MessageCircle size={17}/>Pedir agora</a></div></header>
<section id="inicio" className="border-b border-white/10"><div className="mx-auto grid max-w-7xl items-center gap-10 px-5 py-12 md:grid-cols-2 md:px-8 md:py-20"><div><div className="mb-5 inline-flex items-center gap-2 rounded-full border border-[#a7b86a]/30 bg-[#a7b86a]/10 px-3 py-1 text-xs font-bold uppercase tracking-[.18em] text-[#c9d88c]"><Sparkles size={14}/>Juiz de Fora</div><h1 className="text-5xl font-black leading-[.95] tracking-tight md:text-7xl">Comida de verdade.<br/><span className="text-[#a7b86a]">Prática e saborosa.</span></h1><p className="mt-6 max-w-xl text-lg leading-8 text-white/65">Marmitas Fit, Performance, Tradicional, Premium, saladas e sucos para deixar sua rotina mais simples.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><a href="#cardapio" className="inline-flex items-center justify-center gap-2 rounded-full bg-[#a7b86a] px-6 py-3.5 font-black text-black">Ver cardápio <ArrowRight size={18}/></a><a href={whatsapp} className="inline-flex items-center justify-center gap-2 rounded-full border border-white/15 bg-white/5 px-6 py-3.5 font-bold">Pedir pelo WhatsApp <MessageCircle size={18}/></a></div><div className="mt-8 flex flex-wrap gap-5 text-sm text-white/55"><span className="inline-flex gap-2"><Check className="text-[#a7b86a]" size={16}/>Feitas para a rotina</span><span className="inline-flex gap-2"><Check className="text-[#a7b86a]" size={16}/>Opções variadas</span><span className="inline-flex gap-2"><Check className="text-[#a7b86a]" size={16}/>Entrega em Juiz de Fora</span></div></div><div className="relative overflow-hidden rounded-[2rem] border border-white/10"><img src="/images/hero.jpg" alt="Marmita Nutrifit" className="aspect-[4/3] w-full object-cover"/><div className="absolute inset-x-0 bottom-0 bg-gradient-to-t from-black via-black/30 to-transparent p-7 pt-24"><div className="text-xs font-bold uppercase tracking-[.18em] text-[#a7b86a]">Destaque da casa</div><div className="text-2xl font-black">Patinho com abóbora</div><div className="font-black text-[#ef7d18]">R$ 19,90 • 350 g</div></div></div></div></section>
<section id="cardapio" className="mx-auto max-w-7xl px-5 py-20 md:px-8"><div className="text-sm font-black uppercase tracking-[.2em] text-[#ef7d18]">Cardápio</div><h2 className="mt-2 text-4xl font-black md:text-5xl">Escolha sua Nutrifit</h2><div className="mt-10 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{products.map(([name,cat,price,desc,i])=><article key={String(name)} className="overflow-hidden rounded-3xl border border-white/10 bg-white/[.035]"><div className="relative aspect-[4/3] overflow-hidden bg-black"><div className="h-full w-full bg-cover bg-center" style={{backgroundImage:"url(/images/nutrifit-menu.jpg)",backgroundSize:"400% 500%",backgroundPosition:pos(Number(i))}}/><div className="absolute left-3 top-3 rounded-full bg-[#a7b86a] px-3 py-1 text-[11px] font-black text-black">{cat}</div></div><div className="p-5"><div className="flex items-start justify-between gap-3"><h3 className="text-lg font-black">{name}</h3><span className="whitespace-nowrap font-black text-[#ef7d18]">{price}</span></div><p className="mt-2 text-sm leading-6 text-white/55">{desc}</p><a href={whatsapp} className="mt-5 inline-flex items-center gap-2 text-sm font-bold text-[#c9d88c]">Pedir pelo WhatsApp <ArrowRight size={15}/></a></div></article>)}</div></section>
<section id="sucos" className="border-y border-white/10 bg-[#10130d]"><div className="mx-auto max-w-7xl px-5 py-20 md:px-8"><div className="text-sm font-black uppercase tracking-[.2em] text-[#a7b86a]">Sucos naturais</div><h2 className="mt-2 text-4xl font-black md:text-5xl">500 ml • R$ 12,90</h2><div className="mt-8 grid grid-cols-2 gap-4 sm:grid-cols-3 md:grid-cols-6">{juices.map(j=><a key={j} href={whatsapp} className="rounded-2xl border border-white/10 bg-black/20 p-5 text-center"><div className="text-xl font-black">{j}</div><div className="mt-2 text-sm text-white/50">500 ml</div><div className="mt-3 font-black text-[#ef7d18]">R$ 12,90</div></a>)}</div></div></section>
<section id="combos" className="mx-auto max-w-7xl px-5 py-20 md:px-8"><div className="text-sm font-black uppercase tracking-[.2em] text-[#ef7d18]">Combos Linha Tradicional • 500 g</div><h2 className="mt-2 text-4xl font-black md:text-5xl">Economize no seu pedido</h2><div className="mt-8 grid gap-4 md:grid-cols-3">{combos.map(([q,p])=><a key={q} href={whatsapp} className="flex items-center justify-between rounded-2xl border border-white/10 bg-white/[.035] p-6"><span className="font-bold">{q}</span><span className="font-black text-[#ef7d18]">{p}</span></a>)}</div></section>
<section id="como-pedir" className="border-t border-white/10 bg-[#0f110d]"><div className="mx-auto max-w-7xl px-5 py-20 md:px-8"><div className="grid gap-5 md:grid-cols-3">{[["01","Escolha","Selecione seus pratos."],["02","Envie","Clique no WhatsApp e mande seu pedido."],["03","Receba","Combine entrega e pagamento."]].map(([n,t,d])=><div key={n} className="rounded-3xl border border-white/10 bg-white/[.03] p-7"><div className="text-sm font-black text-[#ef7d18]">{n}</div><h3 className="mt-3 text-2xl font-black">{t}</h3><p className="mt-3 leading-7 text-white/55">{d}</p></div>)}</div><div className="mt-10 flex flex-col justify-between gap-5 rounded-[2rem] border border-[#a7b86a]/20 bg-[#171c11] p-8 md:flex-row md:items-center"><div><div className="text-sm font-bold uppercase tracking-[.2em] text-[#a7b86a]">Pedido rápido</div><div className="mt-2 text-3xl font-black">Fale com a Nutrifit</div><div className="mt-2 text-white/55">(32) 99803-0038 • @nutrifit_jf</div></div><a href={whatsapp} className="inline-flex items-center gap-2 rounded-full bg-[#ef7d18] px-6 py-3 font-black text-black"><ShoppingBag size={18}/>Iniciar pedido</a></div></div></section>
<footer className="border-t border-white/10"><div className="mx-auto flex max-w-7xl justify-between px-5 py-8 text-sm text-white/45 md:px-8"><span>© 2026 Nutrifit • Juiz de Fora</span><span>@nutrifit_jf</span></div></footer></main>}
