"use client";

import { useMemo, useState } from "react";
import { Home, Search, ShoppingBag, UserRound, Plus, Minus, X, Heart, ChevronRight, MapPin } from "lucide-react";

type Product={id:string;name:string;line:string;weight:string;price:number;image:string;description:string};
const products:Product[]=[
{id:"1",name:"Patinho com Abóbora",line:"FIT",weight:"350 g",price:23.97,image:"/images/page-4.jpg",description:"Patinho moído com abóbora cremosa."},
{id:"2",name:"Patinho com Batata-Doce",line:"FIT",weight:"350 g",price:23.97,image:"/images/page-9.jpg",description:"Patinho moído com batata-doce."},
{id:"3",name:"Frango Grelhado com Mix de Legumes",line:"FIT",weight:"350 g",price:23.97,image:"/images/page-6.jpg",description:"Frango grelhado e mix de legumes."},
{id:"4",name:"Carne Acebolada com Legumes",line:"FIT",weight:"350 g",price:23.97,image:"/images/page-5.jpg",description:"Carne bovina acebolada com legumes."},
{id:"5",name:"Chicken Parmesão",line:"PERFORMANCE",weight:"450 g",price:27.90,image:"/images/page-12.jpg",description:"Frango, parmesão, arroz integral e legumes."},
{id:"6",name:"Tilápia Power",line:"PERFORMANCE",weight:"450 g",price:27.90,image:"/images/page-13.jpg",description:"Tilápia, arroz integral, batata-doce e legumes."},
{id:"7",name:"Parmegiana Cremosa",line:"TRADICIONAL",weight:"500 g",price:26.90,image:"/images/page-29.jpg",description:"Frango, molho artesanal, queijo, arroz e purê."},
{id:"8",name:"Churrasco Fit Mineiro",line:"TRADICIONAL",weight:"500 g",price:29.90,image:"/images/page-32.jpg",description:"Carne grelhada, vinagrete, arroz e farofa."},
{id:"9",name:"Suco de Laranja",line:"SUCOS",weight:"500 ml",price:12.90,image:"/images/page-42.jpg",description:"Suco natural e refrescante."},
{id:"10",name:"Sanduíche de Frango",line:"LANCHES",weight:"1 un.",price:12.90,image:"/images/sanduiche-frango-nutrifit.jpg",description:"Pão integral, frango, alface e tomate."}
];
const combos=[{q:5,v:117},{q:7,v:164},{q:10,v:235},{q:14,v:328},{q:20,v:459}];
const money=(n:number)=>n.toLocaleString("pt-BR",{style:"currency",currency:"BRL"});

export default function NutrifitApp(){
 const [tab,setTab]=useState("inicio"),[cat,setCat]=useState("TODOS"),[search,setSearch]=useState(""),[cart,setCart]=useState<Record<string,number>>({}),[detail,setDetail]=useState<Product|null>(null),[comboQty,setComboQty]=useState(0),[combo,setCombo]=useState<string[]>([]);
 const list=useMemo(()=>products.filter(p=>(cat==="TODOS"||p.line===cat)&&((p.name+" "+p.line).toLowerCase().includes(search.toLowerCase()))),[cat,search]);
 const items=products.filter(p=>cart[p.id]),count=Object.values(cart).reduce((a,b)=>a+b,0),total=items.reduce((s,p)=>s+p.price*(cart[p.id]||0),0);
 const add=(id:string)=>setCart(c=>({...c,[id]:(c[id]||0)+1}));
 const sub=(id:string)=>setCart(c=>{const x={...c},n=(x[id]||0)-1;n<=0?delete x[id]:x[id]=n;return x});
 return <main className="min-h-screen bg-[#080a07] text-white pb-24">
  <header className="sticky top-0 z-30 border-b border-white/10 bg-[#080a07]/95 backdrop-blur"><div className="mx-auto flex max-w-6xl items-center justify-between px-4 py-3"><button onClick={()=>setTab("inicio")} className="flex items-center gap-2"><span className="grid h-10 w-10 place-items-center rounded-xl bg-white text-sm font-black text-black">NF</span><b className="text-lg">Nutrifit</b></button><button onClick={()=>setTab("carrinho")} className="relative rounded-full border border-white/10 p-2.5"><ShoppingBag size={20}/>{count>0&&<span className="absolute -right-1 -top-1 rounded-full bg-[#ef7d18] px-1.5 text-[10px] font-black text-black">{count}</span>}</button></div></header>
  {tab==="inicio"&&<section className="mx-auto max-w-6xl px-4 pt-5"><div className="rounded-[2rem] bg-gradient-to-br from-[#a7b86a] to-[#6f7f38] p-6 text-black"><span className="text-xs font-black uppercase tracking-[.18em]">Nutrifit • Juiz de Fora</span><h1 className="mt-2 text-3xl font-black sm:text-5xl">Sua refeição saudável, do seu jeito.</h1><p className="mt-3 max-w-md text-sm text-black/70">Escolha suas refeições, monte seu combo e faça seu pedido pelo celular.</p><button onClick={()=>setTab("cardapio")} className="mt-5 rounded-full bg-black px-5 py-3 text-sm font-black text-white">Ver cardápio</button></div><div className="mt-4 grid grid-cols-3 gap-2"><button onClick={()=>setTab("combos")} className="rounded-2xl border border-white/10 bg-white/[.03] p-3 text-left"><b className="text-sm">Combos</b><span className="block text-[10px] text-white/40">Economize</span></button><div className="rounded-2xl border border-white/10 bg-white/[.03] p-3"><b className="text-sm">Entrega</b><span className="block text-[10px] text-white/40">Juiz de Fora</span></div><div className="rounded-2xl border border-white/10 bg-white/[.03] p-3"><b className="text-sm">Plano</b><span className="block text-[10px] text-white/40">Nutricionista</span></div></div></section>}
  {(tab==="inicio"||tab==="cardapio")&&<section className="mx-auto max-w-6xl px-4 pt-7"><div className="flex items-end justify-between"><div><span className="text-xs font-black uppercase tracking-[.15em] text-[#a7b86a]">Cardápio</span><h2 className="text-2xl font-black">Escolha sua refeição</h2></div></div><div className="mt-4 flex items-center gap-2 rounded-2xl border border-white/10 bg-white/[.03] px-3 py-2"><Search size={17} className="text-white/35"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar prato..." className="w-full bg-transparent py-1 text-sm outline-none"/></div><div className="mt-3 flex gap-2 overflow-x-auto pb-1">{["TODOS","FIT","PERFORMANCE","TRADICIONAL","SUCOS","LANCHES"].map(x=><button key={x} onClick={()=>setCat(x)} className={"whitespace-nowrap rounded-full px-4 py-2 text-[10px] font-black "+(cat===x?"bg-[#ef7d18] text-black":"bg-white/5 text-white/55")}>{x}</button>)}</div><div className="mt-5 grid grid-cols-2 gap-3 md:grid-cols-3 lg:grid-cols-4">{list.map(p=><article key={p.id} className="overflow-hidden rounded-3xl border border-white/10 bg-[#10130d]"><button onClick={()=>setDetail(p)} className="w-full text-left"><img src={p.image} alt={p.name} className="aspect-square w-full object-cover"/><div className="p-3"><span className="text-[9px] font-black uppercase tracking-[.12em] text-[#a7b86a]">{p.line} • {p.weight}</span><h3 className="mt-1 min-h-10 text-sm font-black">{p.name}</h3><p className="mt-1 line-clamp-2 text-[10px] text-white/40">{p.description}</p><div className="mt-3 flex items-center justify-between"><b>{money(p.price)}</b><span className="grid h-8 w-8 place-items-center rounded-full bg-[#ef7d18] text-black"><Plus size={16}/></span></div></div></button></article>)}</div></section>}
  {tab==="combos"&&<section className="mx-auto max-w-5xl px-4 pt-6"><button onClick={()=>setTab("inicio")} className="mb-4 text-sm font-bold text-white/55">← Voltar</button><div className="rounded-[2rem] border border-[#ef7d18]/30 bg-[#1a1008] p-5"><span className="text-xs font-black uppercase tracking-[.15em] text-[#ef7d18]">Monte seu combo</span><h1 className="mt-1 text-3xl font-black">Escolha quantas marmitas</h1><div className="mt-5 grid grid-cols-2 gap-2 sm:grid-cols-5">{combos.map(c=><button key={c.q} onClick={()=>{setComboQty(c.q);setCombo([])}} className={"rounded-2xl border p-4 text-left "+(comboQty===c.q?"border-[#ef7d18] bg-[#ef7d18] text-black":"border-white/10 bg-white/[.03]")}><b className="text-xl">{c.q}</b><span className="block text-xs">{money(c.v)}</span></button>)}</div>{comboQty>0&&<><div className="mt-5 text-sm font-bold">{combo.length}/{comboQty} marmitas escolhidas</div><div className="mt-3 grid grid-cols-2 gap-3 md:grid-cols-3">{products.filter(p=>p.line!=="SUCOS"&&p.line!=="LANCHES").map(p=><button key={p.id} disabled={combo.length>=comboQty&&!combo.includes(p.id)} onClick={()=>setCombo(x=>x.includes(p.id)?x:x.length<comboQty?[...x,p.id]:x)} className={"overflow-hidden rounded-2xl border text-left "+(combo.includes(p.id)?"border-[#a7b86a]":"border-white/10")}><img src={p.image} alt="" className="aspect-square w-full object-cover"/><div className="p-2 text-xs font-bold">{p.name}</div></button>)}</div><button disabled={combo.length!==comboQty} onClick={()=>{combo.forEach(add);setTab("carrinho");setCombo([]);setComboQty(0)}} className="mt-5 w-full rounded-full bg-[#ef7d18] py-3 text-sm font-black text-black disabled:opacity-30">Adicionar combo ao carrinho</button></>}</div></section>}
  {tab==="carrinho"&&<section className="mx-auto max-w-2xl px-4 pt-6"><h1 className="text-3xl font-black">Seu carrinho</h1>{items.length===0?<div className="mt-5 rounded-3xl border border-white/10 p-8 text-center"><ShoppingBag className="mx-auto text-white/30"/><p className="mt-3 text-sm text-white/45">Seu carrinho está vazio.</p><button onClick={()=>setTab("cardapio")} className="mt-4 rounded-full bg-[#ef7d18] px-5 py-3 text-sm font-black text-black">Escolher refeições</button></div>:<><div className="mt-5 space-y-3">{items.map(p=><div key={p.id} className="flex gap-3 rounded-2xl border border-white/10 bg-white/[.03] p-3"><img src={p.image} alt="" className="h-20 w-20 rounded-xl object-cover"/><div className="flex-1"><b className="text-sm">{p.name}</b><div className="mt-2 flex items-center gap-2"><button onClick={()=>sub(p.id)} className="rounded-full bg-white/10 p-1"><Minus size={13}/></button><b className="text-xs">{cart[p.id]}</b><button onClick={()=>add(p.id)} className="rounded-full bg-white/10 p-1"><Plus size={13}/></button></div></div><b>{money(p.price*(cart[p.id]||0))}</b></div>)}</div><div className="mt-5 rounded-3xl border border-white/10 p-5"><div className="flex justify-between"><span className="text-white/50">Subtotal</span><b>{money(total)}</b></div><button onClick={()=>setTab("checkout")} className="mt-5 w-full rounded-full bg-[#ef7d18] py-3 text-sm font-black text-black">Continuar pedido</button></div></>}</section>}
  {tab==="checkout"&&<section className="mx-auto max-w-2xl px-4 pt-6"><button onClick={()=>setTab("carrinho")} className="text-sm font-bold text-white/55">← Carrinho</button><h1 className="mt-4 text-3xl font-black">Finalizar pedido</h1><div className="mt-5 space-y-3"><input placeholder="Seu nome" className="w-full rounded-2xl border border-white/10 bg-white/[.04] px-4 py-3 outline-none"/><input placeholder="WhatsApp" className="w-full rounded-2xl border border-white/10 bg-white/[.04] px-4 py-3 outline-none"/><input placeholder="Endereço de entrega" className="w-full rounded-2xl border border-white/10 bg-white/[.04] px-4 py-3 outline-none"/><div className="rounded-2xl bg-[#a7b86a]/10 p-4 text-sm text-white/65"><MapPin size={17} className="mr-2 inline text-[#a7b86a]"/>O frete será calculado conforme a região de entrega.</div><button onClick={()=>window.open("https://wa.me/5532998030038?text=Olá%20Nutrifit!%20Quero%20finalizar%20meu%20pedido%20pelo%20app.","_blank")} className="w-full rounded-full bg-[#ef7d18] py-3 text-sm font-black text-black">Enviar pedido pelo WhatsApp</button></div></section>}
  {tab==="perfil"&&<section className="mx-auto max-w-2xl px-4 pt-6"><h1 className="text-3xl font-black">Minha conta</h1><div className="mt-5 space-y-2">{["Meus pedidos","Endereços","Meus dados","Plano nutricional","Cupons e benefícios","Falar com a nutricionista"].map(x=><button key={x} className="flex w-full items-center justify-between rounded-2xl border border-white/10 bg-white/[.03] p-4 text-sm font-bold">{x}<ChevronRight size={17} className="text-white/30"/></button>)}</div></section>}
  {detail&&<div className="fixed inset-0 z-50 flex items-end bg-black/70 p-3 sm:items-center"><div className="mx-auto w-full max-w-lg rounded-[2rem] border border-white/10 bg-[#10130d] p-4"><button onClick={()=>setDetail(null)} className="float-right rounded-full bg-white/10 p-2"><X size={17}/></button><img src={detail.image} alt={detail.name} className="aspect-video w-full rounded-3xl object-cover"/><div className="p-2 pt-4"><span className="text-xs font-black text-[#a7b86a]">{detail.line} • {detail.weight}</span><h2 className="mt-1 text-2xl font-black">{detail.name}</h2><p className="mt-2 text-sm text-white/50">{detail.description}</p><div className="mt-5 flex items-center justify-between"><b className="text-2xl">{money(detail.price)}</b><button onClick={()=>{add(detail.id);setDetail(null)}} className="rounded-full bg-[#ef7d18] px-5 py-3 text-sm font-black text-black">Adicionar</button></div></div></div></div>}
  <nav className="fixed inset-x-3 bottom-3 z-40 mx-auto max-w-lg rounded-2xl border border-white/10 bg-[#10130d]/95 p-2 backdrop-blur"><div className="grid grid-cols-4 gap-1">{[["inicio","Início",Home],["cardapio","Cardápio",Search],["combos","Combos",Heart],["perfil","Conta",UserRound]].map(([id,label,I]:any)=><button key={id} onClick={()=>setTab(id)} className={"flex flex-col items-center gap-1 rounded-xl py-2 text-[10px] font-black "+(tab===id?"bg-[#a7b86a] text-black":"text-white/55")}><I size={17}/>{label}</button>)}</div></nav>
 </main>
}
